---

#Download Openvpn Server
- name: Download openVPNServer
  get_url: url={{ openVPNServer_url }} dest={{ VPN_home }} validate_certs=False
 
#Install OpenVPN server

- name: Install OpenVPN
  shell: rpm -Uvh openvpn.rpm
  ignore_errors: True

- name: change openvpn user password
  user: name={{ openvpn_user }} state=present password={{ openvpn_encrypted_password }} shell=/bin/bash
