---

#TRAEFIK

- name: Copy traefik.service
  template: src=traefik.service dest=/etc/systemd/system/traefik.service

- name: Restart systemctl dameon 
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: traefik
