---

# Configuracion COMUN

#Stop firewalld
- name: Check if Service Exists
  stat: path=/usr/sbin/firewalld
  register: firewall_exists

- name: Stop and disable firewall
  shell: systemctl stop firewalld && systemctl disable firewalld
  when: firewall_exists.stat.exists

# Disable SELinux
- name: Disable SELinux
  selinux:
    state: disabled

# Install Kubeadm, Kubelet and Kubectl
- name: Copy kubernetes.repo
  template: src=kubernetes.repo.j2 dest={{ yum_repos }}/kubernetes.repo 

- name: Install kubeadm, kubelet and kubectl
  command: yum -y install {{ item }}
  with_items:
     - kubelet
     - kubeadm
     - kubectl
  args:
    warn: no

- name: Start/Enable Kubelet 
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: yes

- name: Copy k8s.conf
  template: src=k8s.conf.j2 dest=/etc/sysctl.d/k8s.conf

- name: Update sysctl system
  command: sysctl --system

- name: Restart Kubelet 
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
