---
# Kubernetes

- hosts: masters_public:workers_public
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: update_hosts
  - role: docker
  - role: common
  - role: update_hosts
  - role: disable_swap

- hosts: bastion_public
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: haproxy

- hosts: masters_public
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: etcd
#  - role: keepalived

- hosts: masters_public
  remote_user: "{{ user }}"
  become: True
  serial: "1"
  roles:
  - role: initialize_masters

- hosts: masters_public[0]
  remote_user: "{{ user }}"
  become: False
  serial: "100%"
  roles:
  - role: calico_network

- hosts: masters_public[0]
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: register_kubeadm_join

- hosts: workers_public
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: join_workers

- hosts: masters_public[0]
  remote_user: "{{ user }}"
  become: False
  serial: "100%"
  roles:
  - role: dashboard


