---

# Configuracion COMUN

#Stop firewalld
- name: Check if Service Exists
  stat: path=/usr/sbin/firewalld
  register: firewall_exists

- name: Stop and disable firewall
  shell: systemctl stop firewalld && systemctl disable firewalld
  when: firewall_exists.stat.exists

# Disable SELinux
- name: Disable SELinux
  selinux:
    state: disabled

# Install Kubeadm, Kubelet and Kubectl
- name: Copy kubernetes.repo
  template: src=kubernetes.repo.j2 dest={{ yum_repos }}/kubernetes.repo 

- name: Add kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes yum repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: no

- name: Install kubeadm, kubelet and kubectl
  yum: name={{ item }} state=installed
  with_items:
     - kubelet
     - kubeadm
     - kubectl

- name: Start/Enable Kubelet 
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: yes

- name: Copy k8s.conf
  template: src=k8s.conf.j2 dest=/etc/sysctl.d/k8s.conf

- name: Update sysctl system
  command: sysctl --system

- name: Restart Kubelet 
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
