{
 "title": "Kubernetes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_Active{job=\"k8s-agent\"}) / sum(node_memory_MemTotal{job=\"k8s-agent\"}))*100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((count(node_cpu{mode=\"idle\", job=\"k8s-agent\"})-sum(irate(node_cpu{job=\"k8s-agent\",mode=\"idle\"}[5m]))) / (count(node_cpu{mode=\"idle\", job=\"k8s-agent\"})))*100"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\"}) - sum(node_filesystem_avail{job=\"k8s-agent\", mountpoint=\"/\", device=\"rootfs\"})) / (sum(node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\"})) *100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_Active{job=\"k8s-agent\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{job=\"k8s-agent\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"idle\", job=\"k8s-agent\"})-sum(irate(node_cpu{job=\"k8s-agent\",mode=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"idle\", job=\"k8s-agent\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\"}) - sum(node_filesystem_avail{job=\"k8s-agent\", mountpoint=\"/\", device=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\"}) "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_Active{job=\"k8s-agent\"}) / (node_memory_MemTotal{job=\"k8s-agent\"}))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((count(node_cpu{mode=\"idle\", job=\"k8s-agent\", instance=\"172.16.8.232:9100\"})-sum(irate(node_cpu{job=\"k8s-agent\",mode=\"idle\",  instance=\"172.16.8.232:9100\"}[5m]))) / (count(node_cpu{mode=\"idle\", job=\"k8s-agent\", instance=\"172.16.8.232:9100\"})))*100",
     "legendFormat": "K8S-Slave1"
    },
    {
     "expr": "((count(node_cpu{mode=\"idle\", job=\"k8s-agent\", instance=\"172.16.8.233:9100\"})-sum(irate(node_cpu{job=\"k8s-agent\",mode=\"idle\",  instance=\"172.16.8.233:9100\"}[5m]))) / (count(node_cpu{mode=\"idle\", job=\"k8s-agent\", instance=\"172.16.8.233:9100\"})))*100",
     "legendFormat": "K8S-Slave2"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\", instance=\"172.16.8.232:9100\"}) - (node_filesystem_avail{job=\"k8s-agent\", mountpoint=\"/\", device=\"rootfs\", instance=\"172.16.8.232:9100\"})) / (node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\", instance=\"172.16.8.232:9100\"}))*100",
     "legendFormat": "K8S-Slave1"
    },
    {
     "expr": "(((node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\", instance=\"172.16.8.233:9100\"}) - (node_filesystem_avail{job=\"k8s-agent\", mountpoint=\"/\", device=\"rootfs\", instance=\"172.16.8.233:9100\"})) / (node_filesystem_size{job=\"k8s-agent\", mountpoint=\"/\",device=\"rootfs\", instance=\"172.16.8.233:9100\"}))*100",
     "legendFormat": "K8S-Slave2"
    }
   ]
  },
  {
   "title": "Connected Agent Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_boot_time{job=\"k8s-agent\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Connected Agent Nodes",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_boot_time{job=\"k8s-agent\"})"
    }
   ]
  },
  {
   "title": "K8S Nodes Up time",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "node_boot_time{job=~\"k8s-agent|k8s-master\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}