{
 "title": "Spark Kafka Consumer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reamining memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_BlockManager_memory_remainingMem_MB"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_DAGScheduler_job_activeJobs"
    }
   ]
  },
  {
   "title": "Waiting Batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_Spark_consumer_demo_StreamingMetrics_streaming_waitingBatches",
     "legendFormat": "Spark Consumer Demo"
    }
   ]
  },
  {
   "title": "Processed records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_Spark_consumer_demo_StreamingMetrics_streaming_totalProcessedRecords",
     "legendFormat": "Spark Consumer Demo"
    }
   ]
  },
  {
   "title": "Received Batch Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_Spark_consumer_demo_StreamingMetrics_streaming_lastReceivedBatch_records",
     "legendFormat": "Spark Consumer Demo"
    }
   ]
  },
  {
   "title": "Unprocessed Batches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_Spark_consumer_demo_StreamingMetrics_streaming_unprocessedBatches",
     "legendFormat": "Spark Consumer Demo"
    }
   ]
  },
  {
   "title": "Processing Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "app_20180601113236_0017_driver_Spark_consumer_demo_StreamingMetrics_streaming_lastCompletedBatch_processingDelay",
     "legendFormat": "Spark Consumer Demo"
    }
   ]
  }
 ]
}