---

# Kubeadm join command

- name: Read and register kubeadm join command with token
  command: kubeadm token create --print-join-command
  register: kubeadm_token

- name: check keys (DEBUG MODE)
  debug: msg="{{ hostvars[groups['masters_public'][0]]['kubeadm_token'] }}"

- name: check keys option 2!!!!(DEBUG MODE)
  debug: msg="{{ hostvars[groups['masters_public'][0]]['kubeadm_token'].stdout }}"
