---

#DOCKER ALL NODES

#Docker install
- name: Update Centos
  yum: name=* state=latest

- name: Install Docker
  yum: name=docker state=installed

- name: Check if docker has been installed
  stat:
    path: "{{ scaffolding_dir }}/docker_installed_restarted"
  register: docker_installed_restarted

#Reboot to apply docker installation
- name: reboot host
  command: /usr/bin/systemd-run --on-active=10 /usr/bin/systemctl reboot
  async: 0
  poll: 0
  when: docker_installed_restarted.stat.exists == False

- name: Create file to know that docker has been installed and instances restarted
  file: 
    dest: "{{ scaffolding_dir }}/docker_installed_restarted"
    state: touch
    owner: "{{ user }}"
    mode: 0644
  when: docker_installed_restarted.stat.exists == False

#Wait for start
- name: wait for host ssh
  become: false
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=500 delay=60
  when: docker_installed_restarted.stat.exists == False

#Start and enable docker
- name: Start/Enable Docker service 
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: docker
