---

#MASTER & SLAVES

- hosts: masters_public[0]:workers_public
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: java8
  - role: common

- hosts: masters_public[0]
  remote_user: "{{ user }}"
  become: True
  serial: "100%"
  roles:
  - role: start-spark
